author=text->author.name
author=_2->author.department
author=_3->author.Institution
author=_p->author.country
author=_c->author.city
pages=_l->page.last
pages=_f->page.first
title=text->title
title=_i->title.language

lixo=x->x